### ISSUE TITLE
Question regarding the video proxy

### ISSUE THREAD

**Issue by LightRO** [nebulabroadcast/nebula#16]
I have one more question.

Everything seems to be working fine now, but the video I uploaded is not available at https://url/proxy/0000/1.mp4. Under Jobs the video is still on Waiting but nothing happens. In the Firefly on the left side is also the name of the video, but in red there.

I do not get an error message except that CasparCG could not be reached yet, but as far as I know I did not need him at this step right?

Many greetings,
LightRO

**Comment by LightRO** [comment]
Error Message, when i send the movie to proxy:

`2022-10-15 23:01:30 ERROR      conv            Exception!

    Traceback (most recent call last):
      File "/opt/nebula/cli/run.py", line 62, in run
        service.on_main()
      File "/opt/nebula/services/conv/__init__.py", line 106, in on_main
        result = self.encoder.configure()
      File "/opt/nebula/services/conv/encoders.py", line 53, in configure
        target_rel_path = eval(p.text)
      File "<string>", line 1
        /nebula/storage2/playout/proxy/
        ^
    SyntaxError: invalid syntax`

**Comment by LightRO** [comment]
I have found the Error. This was my issue by Path Name.
