### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by aladinko** [nebulabroadcast/nebula#2]
Hello, only info for You. There is a problem with HUB.

```
[23/Nov/2018:14:48:30] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/nebula/vendor/cherryadmin/cherryadmin/handler.py", line 153, in default
    view.build(*args, **kwargs)
  File "/opt/nebula/hub/view_dashboard.py", line 16, in build
    custom_dash = self["user"]["dashboard"]
KeyError: 'dashboard'
[23/Nov/2018:14:48:30] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost
  X-REAL-IP: 127.0.0.1
  CONNECTION: close
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
  REFERER: http://localhost/
  COOKIE: session_id=e1900e153cf9c059bcbd762cdcb92564470c3ea1
  UPGRADE-INSECURE-REQUESTS: 1
127.0.0.1 - - [23/Nov/2018:14:48:30] "GET / HTTP/1.0" 500 4117 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"

```

**Comment by aladinko** [comment]
It helped.
Thank You!
