### ISSUE TITLE
ImportError: No module named 'ccginfo'

### ISSUE THREAD

**Issue by michaeltoohig** [nebulabroadcast/nebula#3]
When I try to start the `play` service I get the following:

```
2019-05-28 09:43:29 WARNING     Nebula          Plugin root dir does not exist
2019-05-28 09:43:29 ERROR       play            Exception!

    Traceback (most recent call last):
      File "./manage.py", line 46, in <module>
        modules[module](*args)
      File "/home/michael/Projects/nebula/nebula/cli/run.py", line 44, in run
        _module = __import__("services." + agent, globals(), locals(), ["Service"])
      File "/home/michael/Projects/nebula/nebula/services/play/__init__.py", line 9, in <module>
        from .caspar_controller import *
      File "/home/michael/Projects/nebula/nebula/services/play/caspar_controller.py", line 16, in <module>
        from ccginfo import *
    ImportError: No module named 'ccginfo'
```

I'm not sure where I am missing the `ccginfo`. Did I miss a step in the setup?

Thank you.

**Comment by martastain** [comment]
Thanks for the reporting. We had an error in our git sync script which did not update the dependency list (rex.json). This should be fixed now. 

`make install` now also create systemd unit files, so it is possible to run nebula and nebula-hub using systemd instead of screen, which is more convenient in production (check README)
