### ISSUE TITLE
Hub dashboard 500 Error

### ISSUE THREAD

**Issue by michaeltoohig** [nebulabroadcast/nebula#4]
When logging into Nebula web the first thing I see is this error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/michael/Projects/nebula/nebula/vendor/cherryadmin/cherryadmin/handler.py", line 164, in default
    view.build(*args, **kwargs)
  File "/home/michael/Projects/nebula/nebula/hub/view_dashboard.py", line 52, in build
    "cpu" : status["cpu"],
TypeError: 'NoneType' object is not subscriptable
```

Perhaps this is a part of something I haven't configured correctly, although I'm using the basic config from the nebula-setup. And I followed the `--rex-update` suggestion from #2 

Again thank you.

**Comment by michaeltoohig** [comment]
I restarted nebula via `./nebula.py` and `./manage.py run hub` in a second terminal and this issue did occur.

Originally I had started each process individually in a different terminal `./manage run {1,2,...}` so I could pinpoint where #3 was happening and came across this error.
