### ISSUE TITLE
Installation error: No module named 'promexp'

### ISSUE THREAD

**Issue by LightRO** [nebulabroadcast/nebula#9]
Hello everyone,

I am still in the middle of the installation and get the following error with the command: ./manage.py run hub:

`root@ms000:/opt/nebula# ./manage.py run hub
2021-04-10 21:44:47 INFO        hub             Reloading webtools
2021-04-10 21:44:47 INFO        hub             Reloading API methods
2021-04-10 21:44:47 ERROR       hub             Exception!

    Traceback (most recent call last):
      File "./manage.py", line 46, in <module>
        modules[module](*args)
      File "/opt/nebula/cli/run.py", line 7, in run
        import hub
      File "/opt/nebula/hub/__init__.py", line 19, in <module>
        from .view_metrics import ViewMetrics
      File "/opt/nebula/hub/view_metrics.py", line 5, in <module>
        from promexp.metrics import Metrics
    ModuleNotFoundError: No module named 'promexp'

Can me everyone help me?

Best regards,
LightRO
`

**Comment by martastain** [comment]
Hello, 
check whether a repository github.com/immstudios/promexp is present in the rex.json file (it should be if you are running the latest version).

You may then use the following command to install the missing dependency:

```./nebula.py --rex-update```

Regards

Martin
